# Generated by Django 2.2.2 on 2019-06-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
